### PR TITLE
deadline exceeded detection & session key validation reliability improvement

### PR DESCRIPTION
**Pull request by TimNN**

### CODE REVIEW

**Comment by Felerius** [comment]
Looks quite good. But shouldn't `DEADLINE_EXCEEDED` be another `RelevancyType`? If a student has a submission before and after the deadline, we would probably want to score the one before the deadline, and warn him about submitting after the deadline. If I understand the current implementation correctly, it would only save the latest submission, with a warning about the exceeded deadline.

**Comment by TimNN** [comment]
This was my initial idea, however I changed my mind about the implementation with the following reasoning:

* If there are submissions after the deadline, do we download only those before the deadline or those from before and after the deadline? And if we download both, which submissions should we download after the deadline (top scoring, assessed but not submitted, etc.)?
* Submissions after the deadline should be exceedingly rare and ideally never happen.
* Submissions after the deadline would require an investigation using the codeocean website anyway (at least for me)
* As such I decided to keep the behaviour of the scraper as-is and just create a file to notify the user about the exceeded deadline.

**Comment by Felerius** [comment]
My idea was to filter out everything after the deadline, and check for a submission (i.e. actually submitted, not just assessed), and put a warning file in the main student directory.

But as you mentioned, these submissions should be quite rare, so I think the current behaviour is fine. Will merge, unless there is something you still want to change.

**Comment by TimNN** [comment]
Yeah, that was one of the alternatives I considered but I believe the current behaviour will do just fine. (That mean I don't want to change anything at the moment ;)

**Pull request merged**
