### PR TITLE
sort submission into directories based on their relevancy

### PR DESCRIPTION
**Pull request by TimNN**
This makes the output more suitable for multi-file submissions, although it probably makes the situation worse for single file submissions.

Any suggestions for a solution which would fit both use cases?

### CODE REVIEW

**Comment by Felerius** [comment]
Looks quite good. Two things I would change personally:
* If there is only a single submission, put the files in the main student directory. This would make them easier to access and reserve all caps for the case that something is actually wrong.
* Put the url and score in an `info.txt`, or make their names lowercase, for the same reason regarding all caps as above.

The first change would also make the situation better for single file submissions.

**Comment by TimNN** [comment]
1) That's a good idea, I'll do that
2) I kept them deliberately separate to make it easier for a script to eg. filter submissions by score, but it can change their names to `score.txt` and `url.txt`, would that be ok?

**Comment by Felerius** [comment]
Sounds good, yes. I just like the idea of having all caps for warnings/errors, so you easily find them by looking over the list of folders.

**Comment by Felerius** [comment]
Another thing to do before merging is to adapt the readme the reflect the changes.

**Comment by TimNN** [comment]
Updated.

**Comment by Felerius** [comment]
The folder structure I had in mind is a little bit different, let me elaborate:
 * If there is only a single `SUBMIT` submission put the file(s) plus `score.txt` and `url.txt` in the students folder (`targetDirectory/studentName`).
 * If there is no `SUBMIT` submission, or there are multiple submissions (for example `SUBMIT` and `ASSESSED_AFTER_SUBMIT`), create subdirectories for each submission (eg. `targetDirectory/studentName/SUBMIT`)

The reason for this was to always have `score.txt` and `url.txt` for the script use case you mentioned above, while avoiding unnecessary nested directories. But I'm honestly fine with both solutions, so if you prefer this layout I'll merge it right away. What's your take?

**Comment by TimNN** [comment]
I think the current approach is more uniform (`SUBMIT` submissions are always in the `SUBMIT` directory) also, `score,txt` would need to be in the subdirectories anyways because it may differ from submission to submission.

Thus I would prefer the current layout.

**Pull request merged**
